<html>
	<head>
		<title><?php echo $name ?>你好！</title>
		<link rel="stylesheet" type="text/css" href="/public/css/site.css">
		<link rel="stylesheet" type="text/css" href="/public/css/bootstrap.css">
	</head>
	<body>
		<div id="top-bar">
			<div class="content">
				<span class="fl">欢迎你</span>
				<span class="fr">欢迎你</span>
			</div>
		</div>
		<div id="main" class="border yuanjiao">
			<section>
				<div class="center sbox">
					<form action="/login/index" method="post" class="form-horizontal">
						<?php
							if (!empty($errorMsg)) {
						?>
							<div class="error"><?php echo $errorMsg ?></div>
						<?php
							}
						?>

						<div class="control-group">
						    <label class="control-label" for="inputEmail">用户名：</label>
						    <div class="controls">
						    	<input type="text" name="username" placeholder="用户名">
						    </div>
						</div>
						<div class="control-group">
						    <label class="control-label" for="inputEmail">密码：</label>
						    <div class="controls">
						    	<input type="password" name="password" >
						    </div>
						</div>
						<input type="submit" class="btn" value="登录" />
					</form>
				</div>
			</section>
		</div>
	</body>
</html>