<?php include './application/views/header.php'; ?>
<?php include './application/views/top-nav.php'; ?>
<div id="main" class="container">
	<section>
		<div class="center sbox">
			<form action="/login/index" method="post" class="form-horizontal">
				<?php
					if (!empty($errorMsg)) {
				?>
					<div class="error"><?php echo $errorMsg ?></div>
				<?php
					}
				?>

				<div class="control-group">
				    <label class="control-label" for="inputEmail">用户名：</label>
				    <div class="controls">
				    	<input type="text" name="username" placeholder="用户名">
				    </div>
				</div>
				<div class="control-group">
				    <label class="control-label" for="inputEmail">密码：</label>
				    <div class="controls">
				    	<input type="password" name="password" >
				    </div>
				</div>
				<input type="submit" class="btn" value="登录" />
			</form>
		</div>
	</section>
</div>
<?php include './application/views/footer.php'; ?>