<?php include $webroot . '/views/header.php'; ?>
<?php include $webroot . '/views/top-nav.php'; ?>
	
	<div class="container" style="margin-top: 100px;">
		<h2>注册新用户</h2>
			<div class="error">
				<?php
					if (!empty($errorMsg)) {
						echo $errorMsg;
					}
				 ?>
			</div>
			<form class="form-horizontal" method="post" action="">
				<div class="control-group">
			    	<label class="control-label" for="username">用户名：</label>
			    	<div class="controls">
			      		<input type="text" id="username" name="username" <?php if (!empty($user['username'])) echo 'value=' .$user['username']; ?> placeholder="">
			      		<?php if (!empty($validateErrorMsges['username'])) echo '<span class="help-inline">' . $validateErrorMsges['username'] . '</span>' ?>
			    	</div>
			  	</div>
			  	<div class="control-group">
			    	<label class="control-label" for="email">邮箱：</label>
			    	<div class="controls">
			      		<input type="text" id="email" name="email" placeholder="" <?php if (!empty($user['email'])) echo 'value=' .$user['email']; ?> >
			      		<?php if (!empty($validateErrorMsges['email'])) echo '<span class="help-inline">' . $validateErrorMsges['email'] . '</span>' ?>
			    	</div>
			  	</div>
			 	<div class="control-group">
			    	<label class="control-label" for="password">密码：</label>
			    	<div class="controls">
			      		<input type="password" id="password" name="password" placeholder="">
			      		<?php if (!empty($validateErrorMsges['password'])) echo '<span class="help-inline">' . $validateErrorMsges['password'] . '</span>' ?>
			    	</div>
			  	</div>
			  	<div class="control-group">
			    	<label class="control-label" for="repassword">重复密码：</label>
			    	<div class="controls">
			      		<input type="password" id="repassword" name="repassword" placeholder="">
			      		<?php if (!empty($validateErrorMsges['repassword'])) echo '<span class="help-inline">' . $validateErrorMsges['repassword'] . '</span>' ?>
			    	</div>
			  	</div>
			  	<div class="control-group">
			    	<label class="control-label" for="gender">性别：</label>
			    	<div class="controls">
			    		<select name="gender" class="input-mini">
			    			<option checked="checked" value="male">女</option>
			    			<option value="fmale">男</option>
			    		</select>
			    		<?php if (!empty($validateErrorMsges['gender'])) echo '<span class="help-inline">' . $validateErrorMsges['gender'] . '</span>' ?>
			    	</div>
			  	</div>
			  	<div class="control-group">
			    	<div class="controls">
			    		<input type="hidden" name="_token" value="<?php echo $_SESSION['_token'] ?>">
				      	<button type="submit" class="btn">注册</button>
			    	</div>
			  	</div>
			</form>
	</div>
	<script type="text/javascript">load('reg');</script>
<?php include $webroot . '/views/footer.php'; ?>