<html>
	<head>
		<title><?php echo $name ?>你好！</title>
	</head>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
		}
		body {
			background-image: url(1.jpg);
		}
		#top-bar {
			width: 100%;
			position: fixed;
			height: 40px;
			background: #000;
			margin: 0 auto;
			top: 0px;
			left: 0px;
		}
		#top-bar .content {
			font-size: 18px;
			line-height: 40px;
			color: #fff;
			width: 80%;
			margin: 0 auto;
		}
		#main {
			margin-top: 60px;
			margin-left: auto;
			margin-right: auto;
			width: 80%;
			height: 800px;
		}
		.yuanjiao {
　　			border-radius: 5px;
		}
		.border {
			border: 1px solid #eeeeee;
		}
		.fl {
			float: left;
		}
		.fr {
			float: right;
		}
	</style>
	<body>
		<div id="top-bar">
			<div class="content">
				<span class="fl">欢迎你</span>
				<span class="fr">欢迎你</span>
			</div>
		</div>
		<div id="main" class="border yuanjiao">
			<section>

				Hello World!
			</section>
		</div>
	</body>
</html>